services:
  marquez-db:
    image: postgres:13
    container_name: marquez-db
    environment:
      POSTGRES_USER: marquez
      POSTGRES_PASSWORD: marquez
      POSTGRES_DB: marquez
    ports:
      - "5432:5432"
    volumes:
      - marquez-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marquez -d marquez"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  marquez-api:
    image: marquezproject/marquez:latest
    container_name: marquez-api
    depends_on:
      marquez-db:
        condition: service_healthy
    environment:
      MARQUEZ_PORT: 5000
      MARQUEZ_ADMIN_PORT: 5001
      MARQUEZ_DB_HOST: marquez-db
      MARQUEZ_DB_PORT: 5432
      MARQUEZ_DB: marquez
      MARQUEZ_DB_USERNAME: marquez
      MARQUEZ_DB_PASSWORD: marquez
      MARQUEZ_CONFIG: /marquez/config/config.yml
    volumes:
      - ./config/config.yml:/marquez/config/config.yml
    ports:
      - "5000:5000"   # API
      - "5001:5001"   # Admin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/v1/namespaces"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  marquez-web:
    image: marquezproject/marquez-web:latest
    container_name: marquez-web
    depends_on:
      marquez-api:
        condition: service_healthy
    environment:
      MARQUEZ_HOST: marquez-api
      MARQUEZ_PORT: 5000
      WEB_PORT: 3000
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  marquez-db-data: